#define TAPPING_TERM 185
#define TAPPING_TERM_PER_KEY

#define TAPPING_TOGGLE 2
#define RETRO_TAPPING

// #define RGBLIGHT_DISABLE_KEYCODES
#define RGBLIGHT_LAYERS

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define POINTING_DEVICE_DEBUG



#define LEADER_PER_KEY_TIMING
#define LEADER_TIMEOUT 250
#define LEADER_NO_TIMEOUT

#define UNICODE_SELECTED_MODES UNICODE_MODE_MACOS

// #define UNICODE_SELECTED_MODES UNICODE_MODE_MAC, UNICODE_MODE_LINUX
// #define UNICODE_CYCLE_PERSIST false
