RGBLIGHT_ENABLE = yes # Enable keyboard RGB underglow
EXTRAKEY_ENABLE = yes
COMBO_ENABLE = yes
LEADER_ENABLE = yes
TAP_DANCE_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes
AUTOCORRECT_ENABLE = yes
CONSOLE_ENABLE = yes
CAPS_WORD_ENABLE = yes

UNICODE_COMMON = yes
UNICODE_ENABLE = yes
REPEAT_KEY_ENABLE = yes

